repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        args: [--settings-path=fieldstone,--application-directories=fieldstone]
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        args: [--settings-path=fieldstone]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: flake8
        additional_dependencies:
          - flake8-import-order
          - flake8-quotes
          - flake8-breakpoint
        args: [--config, fieldstone/setup.cfg]
